CUDNN:
  BENCHMARK: true
  DETERMINISTIC: false
  ENABLED: true
GPUS: (0,)
OUTPUT_DIR: 'output'
LOG_DIR: 'log'
WORKERS: 6
PRINT_FREQ: 10

DATASET:
  DATASET: nightcity
  ROOT: '../MRRNet/data/'
  TEST_SET: 'list/nightcity/val.lst'
  TRAIN_SET: 'list/nightcity/train.lst'
  NUM_CLASSES: 19
MODEL:
  NAME: sanet
  NUM_OUTPUTS: 2
  PRETRAINED: 'pretrained_models/cityscapes/mrrnet_s.pt'
LOSS:
  USE_OHEM: true
  OHEMTHRES: 0.9
  OHEMKEEP: 131072
  BALANCE_WEIGHTS: [ 0.4, 1.0 ]
  SB_WEIGHTS: 1.0
TRAIN:
  ExpName: 'SANet_S'
  IMAGE_SIZE:
    - 1024
    - 512
  BASE_SIZE: 1024
  BATCH_SIZE_PER_GPU: 2
  SHUFFLE: true
  BEGIN_EPOCH: 0
  END_EPOCH: 484
  RESUME: false
  OPTIMIZER: sgd
  LR: 0.01
  WD: 0.0005
  MOMENTUM: 0.9
  NESTEROV: true
  FLIP: true
  MULTI_SCALE: true
  IGNORE_LABEL: 255
  SCALE_FACTOR: 16
TEST:
  IMAGE_SIZE:
    - 1024
    - 512
  BASE_SIZE: 1024
  BATCH_SIZE_PER_GPU: 2
  FLIP_TEST: false
  MULTI_SCALE: true
  SCALE_LIST: [ 0.5,0.75,1.0,1.25,1.5,2.0 ]
  MODEL_FILE: 'pretrained_models/cityscapes/mrrnet_s.pt'
  OUTPUT_INDEX: 1
